### ISSUE TITLE
Revise to check all concepts are well explained

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2017-cloud-alife-mini-review#1]
And ask for clarification when they are not.

**Comment by JJ** [comment]
Antonio, we *need* this very urgently.

**Comment by amorag** [comment]
Ok, I'll do it between today and tomorrow. ;)

**Comment by JJ** [comment]
Once again, we need it today. I'll review the paper today and submit it.

**Comment by pacastillo** [comment]
I have read the whole paper and all concepts are clear.
